In [2]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis.
# How does it enhance Python's capabilities for numerical operations?

import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("Array after vectorized addition:", arr + 5)  # Vectorized operation


Original Array: [1 2 3 4]
Array after vectorized addition: [6 7 8 9]


In [3]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy.
# When would you use one over the other?

arr = np.array([10, 20, 30, 40])

print("Mean:", np.mean(arr))              # Simple mean
print("Average (no weights):", np.average(arr))  # Same as mean
weights = [1, 2, 3, 4]
print("Weighted Average:", np.average(arr, weights=weights))  # Weighted average


Mean: 25.0
Average (no weights): 25.0
Weighted Average: 30.0


In [4]:
# 3. Describe the methods for reversing a NumPy array along different axes.
# Provide examples for 1D and 2D arrays.

# Reversing 1D array
arr_1d = np.array([1, 2, 3, 4])
print("Reversed 1D:", arr_1d[::-1])

# Reversing 2D array rows and columns
arr_2d = np.array([[1, 2], [3, 4]])
print("Original 2D:\n", arr_2d)
print("Reversed rows:\n", arr_2d[::-1])
print("Reversed columns:\n", arr_2d[:, ::-1])


Reversed 1D: [4 3 2 1]
Original 2D:
 [[1 2]
 [3 4]]
Reversed rows:
 [[3 4]
 [1 2]]
Reversed columns:
 [[2 1]
 [4 3]]


In [5]:
# 4. How can you determine the data type of elements in a NumPy array?
# Discuss the importance of data types in memory management and performance.

arr = np.array([1.2, 2.3, 3.4])
print("Data type:", arr.dtype)  # Shows data type, e.g., float64

# dtype helps save memory when using appropriate types
small_int_arr = np.array([1, 2, 3], dtype=np.int8)
print("Small int array dtype:", small_int_arr.dtype)


Data type: float64
Small int array dtype: int8


In [6]:
# 5. Define ndarrays in NumPy and explain their key features.
# How do they differ from standard Python lists?

nd_arr = np.array([1, 2, 3])
py_list = [1, 2, 3]

# NumPy supports vectorized operations
print("NumPy ndarray multiplied by 2:", nd_arr * 2)
print("Python list multiplied by 2:", py_list * 2)  # List repeats


NumPy ndarray multiplied by 2: [2 4 6]
Python list multiplied by 2: [1, 2, 3, 1, 2, 3]


In [7]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# NumPy is optimized for speed using C-extensions
arr = np.arange(1_000_000)
print("Sum using NumPy:", np.sum(arr))  # Fast and efficient


Sum using NumPy: 499999500000


In [8]:
# 7. Compare vstack() and hstack() functions in NumPy.
# Provide examples demonstrating their usage and output.

a = np.array([1, 2])
b = np.array([3, 4])

v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print("vstack:\n", v_stacked)  # Vertically stack arrays
print("hstack:\n", h_stacked)  # Horizontally stack arrays


vstack:
 [[1 2]
 [3 4]]
hstack:
 [1 2 3 4]


In [9]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy,
# including their effects on various array dimensions.

mat = np.array([[1, 2], [3, 4]])

print("Original:\n", mat)
print("fliplr (left to right):\n", np.fliplr(mat))  # Flip columns
print("flipud (up to down):\n", np.flipud(mat))     # Flip rows


Original:
 [[1 2]
 [3 4]]
fliplr (left to right):
 [[2 1]
 [4 3]]
flipud (up to down):
 [[3 4]
 [1 2]]


In [10]:
# 9. Discuss the functionality of the array_split() method in NumPy.
# How does it handle uneven splits?

arr = np.array([10, 20, 30, 40, 50])

splits = np.array_split(arr, 3)  # Uneven split handled gracefully
for idx, s in enumerate(splits):
    print(f"Split {idx + 1}:", s)


Split 1: [10 20]
Split 2: [30 40]
Split 3: [50]


In [11]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy.
# How do they contribute to efficient array operations?

arr = np.array([1, 2, 3])
print("Broadcasting scalar (10) to array:", arr + 10)  # Broadcasting

arr2d = np.array([[1], [2], [3]])
print("Broadcasting 1D to 2D:\n", arr2d + arr)  # Broadcasting shapes to match


Broadcasting scalar (10) to array: [11 12 13]
Broadcasting 1D to 2D:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]
